#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2.8
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

### COLORS

source $HOME/.config/bspwm/colors/colors.conf

### RULES ###

bspc rule -a Lxappearance state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a discord desktop='^5'
bspc rule -a firefox desktop='^1'
bspc rule -a Emacs state=tiled

### AUTOSTART ###

bash ~/.config/polybar/launch-bspwm.sh &
bash ~/.config/mk-lang &
nitrogen --restore &
picom &
dunst &
lxsession &
emacs --daemon &
flameshot &

wmname LG3D
