#+title: Polybar Config
#+author: mko

* COLORS
Setting the colors!
#+BEGIN_SRC sh :tangle config.ini
[colors]

disabled = #707880

### DoomOne

background = #282c34
foreground = #bbc2cf
black =      #1c1f24
red =        #ff6c6b
green =      #98be65
yellow =     #ecbe7b
blue =       #51afef
magenta =    #c678dd
cyan =       #5699af
white =      #202328

pink =       #ff92d8

### Dracula

# background =  #282c36
# foreground:   #f8f8f2
# black:        #000000
# red:          #ff5555
# green:        #5af78e
# yellow:       #f1fa8c
# blue:         #bd93f9
# magenta:      #ff79c6
# cyan:         #8be9fd
# white:        #bfbfbf

# pink          #ff92d8


#+END_SRC

* BASE BAR
NOTE: Change the monitor! (do 'xrandr | grep connnected' and look for the connected monitor's name and replace 'HDMI-0' with it.)
#+BEGIN_SRC sh :tangle config.ini
[bar/base]
monitor = HDMI-0
width = 100%
height = 20pt
radius = 0
border-bottom-size = 0
border-top-size = 0
border-left-size = 0
border-right-size = 0

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt

padding-left = 0
padding-right = 0

module-margin = 0

; separator = |
; separator-foreground = ${colors.disabled}

font-0 = SauceCodePro Nerd Font:pixelsize=12;2
font-1 = FontAwesome:pixelsize=16;2

modules-left = archlogo sep i3 sep spotify spotify-prev spotify-play-pause spotify-next
modules-center = date
modules-right = kernel sep cpu sep xkeyboard sep pulseaudio sep network

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = right
; tray-detached = false
; tray-background = ${color.background}
; tray-offset-x = 1000
; tray-offset-y = 0
; tray-padding = 0
; tray-scale = 1.0

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3
#+END_SRC

* SECOND BAR
Second bar template for a second monitor
NOTE: Change the monitor name again.
#+BEGIN_SRC sh :tangle config.ini
[bar/secondary]
monitor = DVI-D-0
width = 100%
height = 18pt
radius = 0
border-bottom-size = 0
border-top-size = 0
border-left-size = 0
border-right-size = 0

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt

padding-left = 0
padding-right = 0

module-margin = 1

font-0 = SauceCodePro Nerd Font:pixelsize=12;2
font-1 = FontAwesome:pixelsize=16;2

modules-left = archlogo sep i3 sep xwindow
modules-center = date
modules-right = xkeyboard sep pulseaudio sep powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
#+END_SRC

* MODULES

These are all of those modules I use in my bars

** KERNEL
Kernel Module to display the kernel version
#+BEGIN_SRC sh :tangle config.ini
[module/kernel]
type = custom/script
exec = uname -r | sed s/1-1//
tail = false
interval = 1024
format-foreground = ${colors.blue}
format-underline = ${colors.blue}
format-prefix = " "
click-left = alacritty --hold -e "neofetch"
#+END_SRC

** SEPERATOR
Seperator module to seperate all the other modules (I don't use the built in polybar module because it conflicts with my spotify modules' button to change songs)
#+BEGIN_SRC sh :tangle config.ini
[module/sep]
type = custom/text
content = |
content-foreground = ${colors.disabled}
content-padding = 1
#+END_SRC

** ARCH LOGO
Just a cool module to display the arch logo at the top left, you can change the emoji to whatever distro (if it's available as an emoji, check the nerd-fonts cheatsheet https://www.nerdfonts.com/cheat-sheet)
#+BEGIN_SRC sh :tangle config.ini
[module/archlogo]
type = custom/text
content = " "
content-foreground = ${colors.blue}
#+END_SRC

** WORKSPACES
The i3wm workspaces module, nothing special here
#+BEGIN_SRC sh :tangle config.ini
[module/i3]
type = internal/i3
format = <label-state> <label-mode>

index-sort = true
wrapping-scroll = false

label-focused = %name%
label-focused-background = ${colors.background}
label-focused-foreground = #ffffff
label-focused-underline = ${colors.blue}
label-focused-padding = 1

label-unfocused = %name%
label-unfocused-foreground = #a9a9a9
label-unfocused-padding = 1

label-visible = %name%
label-visible-background = ${colors.background}
label-visible-underline = ${colors.blue}
label-visible-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.red}
label-urgent-padding = 1

strip-wsnumbers = true

wm-restack = i3
#+END_SRC

** VOLUME
Set the volume through polybar!
Scroll to change the volume level
Middle click the module to open 'pavucontrol' (if you have it installed) for even more audio control.
#+BEGIN_SRC sh :tangle config.ini
[module/pulseaudio]
type = internal/pulseaudio
mapped = true

format-volume = <ramp-volume> <label-volume>
format-volume-underline = ${colors.green}
format-muted-underline = ${colors.red}
label-volume-foreground = ${colors.green}
label-volume = %percentage%%
label-muted = "婢 muted"
interval = 5

label-muted-foreground = ${colors.red}
ramp-volume-foreground = ${colors.green}
ramp-volume-0 = "婢  "
ramp-volume-1 = "墳  "
ramp-volume-1-weight = 5
ramp-volume-2 = "墳"
ramp-volume-2-weight = 90
click-middle = pavucontrol
#+END_SRC

** XKEYBOARD
Choose which keyboard layout you have selected (only works with xorg, hence the X in the name)
#+BEGIN_SRC sh :tangle config.ini
[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.red}

format-prefix = " "
format-foreground = ${colors.red}
format-underline = ${colors.red}
label-indicator-padding = 0
label-indicator-margin = 0.85
label-indicator-foreground = ${colors.red}
label-indicator-background = ${colors.background}
#+END_SRC

** CPU
Shows CPU usage in polybar!
#+BEGIN_SRC sh :tangle config.ini
[module/cpu]
type = internal/cpu

; Seconds to sleep between updates
; Default: 1
interval = 0.5

warn-percentage = 95

; Available tags:
;   <label> (default)
;   <bar-load>
;   <ramp-load>
;   <ramp-coreload>
format = <label>

label =  %percentage%%

label-foreground = ${colors.cyan}
label-underline = ${colors.cyan}

label-warn-foreground = ${colors.red}
label-warn-underline = ${colors.red}

label-warn =  %percentage%%
#+END_SRC

** NETWORK
Shows network usage in polybar!
#+BEGIN_SRC sh :tangle config.ini
[module/network]
type = internal/network
interval = 1.0
interface = enp2s0
format-connected = <label-connected>
format-disconnected = <label-disconnected>

format-connected-prefix = "直"
format-connected-prefix-foreground = ${colors.magenta}
format-connected-foreground = ${colors.magenta}
format-connected-underline = ${colors.magenta}
label-connected = " %upspeed% "
label-foreground = ${colors.magenta}

format-disconnected-prefix = "睊 "
format-disconnected-prefix-foreground = ${colors.red}
format-disconnected-foreground = ${colors.red}
format-disconnected-underline = ${colors.red}
label-disconnected = Disconnected
#+END_SRC

** DATE
Shows the date.
#+BEGIN_SRC sh :tangle config.ini
[module/date]
type = internal/date
interval = 5
date = %A %B %d, %H:%M
label = %date%
label-foreground = ${colors.foreground}

[settings]
screenchange-reload = true
pseudo-transparency = true
#+END_SRC

** SPOTIFY
The next few modules will be packed into one, they're just spotify controls
Dependencies: zscroll, playerctl (zscroll is available in the AUR, playerctl is available in the arch repos)
#+BEGIN_SRC sh :tangle config.ini
[module/spotify]
type = custom/script
tail = true
interval = 1
format-prefix = " "
format-prefix-foreground = ${colors.green}
format-foreground = ${colors.foreground}
format-prefix-underline = ${colors.green}
format-underline = ${colors.green}
; prefix symbol is shown before the text
format = <label>
exec = ~/.config/polybar/scripts/scroll_spotify_status.sh

[module/spotify-prev]
type = custom/script
exec = echo " 玲"
format = <label>
format-underline = ${colors.green}
click-left = playerctl previous -p spotify

[module/spotify-play-pause]
type = custom/ipc
hook-0 = echo " 懶 "
hook-1 = echo " 懶 "
initial = 1
format-underline = ${colors.green}
click-left = playerctl play-pause -p spotify

[module/spotify-next]
type = custom/script
exec = echo "怜"
format = <label>
format-underline = ${colors.green}
click-left = playerctl next -p spotify
#+END_SRC

** POWERMENU
Powermenu, top right of the bar
Click the arch-like logo to show/hide the buttons
Green button launches betterlockscreen (info on betterlockscreen in the i3 config.org)
Yellow button restarts your system
Red button shuts down your system.
#+BEGIN_SRC sh :tangle config.ini
[module/powermenu]
type=custom/menu
expand-right = false

label-open = "ﴂ "
label-open-foreground = ${colors.blue}
label-close = " ﴂ"
label-close-foreground = ${colors.blue}
label-close-padding-right = 8 px

; Shutdown
menu-0-2 = ""
menu-0-2-padding = 8 px
menu-0-2-foreground = ${colors.red}
menu-0-2-exec = shutdown -P now
; Reboot
menu-0-1 = "ﲭ"
menu-0-1-padding = 8 px
menu-0-1-foreground = ${colors.yellow}
menu-0-1-exec = shutdown -r now

; Log out
menu-0-0 = ""
menu-0-0-padding-right = 8 px
menu-0-0-foreground = ${colors.green}
menu-0-0-exec = betterlockscreen -l
#+END_SRC
** BATTERY
Show battery module for laptops
laptop battery module
NOTE: Change the battery and adapter or the module won't appear
#+BEGIN_SRC sh :tangle config.ini
[module/battery]
type = internal/battery

full-at = 99

; Use the following command to list batteries and adapters
;ls -1 /sys/class/power_supply/
battery = BAT1
adapter = ACAD

poll-interval = 5

time-format = $H:$M

format-charging = <animation-charging <label-charging>
format-discharging = <ramp-capacity> <label-discharging>

label-charging = +%percentage%%
label-discharging = -%percentage%%

label-full = 
label-full-foreground = ${colors.blue}
label-full-underline = ${colors.blue}
label-charging-foregrond = ${colors.green}
label-charging-underline = ${colors.green}
label-discharging-foreground = ${colors.red}
label-discharging-underline = ${colors.red}
format-charging-foreground = ${colors.red}
format-charging-underline = ${colors.red}
format-discharging-foreground = ${colors.red}
format-discharging-underline = ${colors.red}

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
; Framerate in milliseconds
animation-discharging-framerate = 500
#+END_SRC
** BRIGHTNESS
Show screen brightness (mostly for use on laptops)
#+BEGIN_SRC sh :tangle config.ini
[module/backlight]
type = internal/backlight

; Use the following command to list available cards
; ls -1 /sys/class/backlight
card = intel_backlight

use-actual-brightness = true

format = <label>

label =  %percentage%%

label-foreground = ${colors.pink}
label-underline = ${colors.pink}
#+END_SRC
